### ISSUE TITLE
Configure CD for releases

### ISSUE THREAD

**Issue by ales-tsurko** [Atleta-network/atleta#109]
We need to configure deploy to github releases of compiled node binaries. It should be compiled for at least linux and macOS.

**Comment by hrls** [comment]
https://github.com/Atleta-network/atleta/pull/151

**Comment by hrls** [comment]
Done
https://github.com/Atleta-network/atleta/commit/254f928ea69adea1344e337ee2834d36b70f344a

https://github.com/Atleta-network/atleta/actions/runs/10282495712
