### ISSUE TITLE
Add new calls to existing precompiles

### ISSUE THREAD

**Issue by hrls** [Atleta-network/atleta#174]
- [x] staking/nominate
- [x] staking/bond
- [x] nominationPools/createPool

**Comment by dlamar228** [comment]
- [x] nominationPools/metadata

**Comment by hrls** [comment]
- [ ] batch createPool with metadata into single call

**Comment by hrls** [comment]
> * [ ]  ~~batch createPool with metadata into single call~~

Pool id is available as event only after extrinsic call.
