### ISSUE TITLE
Batch calls for staking (bond + nominate) and (unbond + chill)

### ISSUE THREAD

**Issue by hrls** [Atleta-network/atleta#200]
- [ ] Ensure we can call unbond after chill

**Comment by DmitriVT** [comment]
We can add utility -> batchAll extrinsic to precompile list. Why do we need to think about separetes batch calls?

**Comment by hrls** [comment]
> We can add utility -> batchAll extrinsic to precompile list.

Yes, this is enough. But we need to filter contents of batch calls to make allow only a specific list of calls, as we've already done.

**Comment by DmitriVT** [comment]
Why do we need filters?
I think check of signature in each extrinsic is more than enough

**Comment by hrls** [comment]
Probably we don't want to allow all available extrinsic calls via EVM-layer.

**Comment by DmitriVT** [comment]
What issue could there be here? I don’t see any problem, considering that in our network all types of extrinsics are already accessible through Polkadot.js Explorer. Also shouldn’t be an issue since our network has validations implemented both at the extrinsic and consensus levels.

**Comment by hrls** [comment]
Idk, it's already here:
https://github.com/Atleta-network/atleta/blob/a9befe24cf01314216f7dcabfbc848c118bbc384/runtime/src/precompiles.rs#L89

**Comment by DmitriVT** [comment]
Still I don't see any problem to add additional RuntimeCall as Utility.
