### ISSUE TITLE
Make it a relay chain

### ISSUE THREAD

**Issue by ales-tsurko** [Atleta-network/atleta#41]

**Comment by hrls** [comment]
As we discussed earlier, here the short list of assumptions:
- eth-related functionality of node are part of relayers;
- we need to introduce new simple parachain which will store some data and communicates with relayers in simple way;

**Comment by hrls** [comment]
https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/client/relay-chain-minimal-node/src
