### ISSUE TITLE
Probably gas limit issues

### ISSUE THREAD

**Issue by ales-tsurko** [Atleta-network/atleta#67]
This is a report from an outsider.

When we deploy it locally using hardhat aave it works:

![image5](https://github.com/Atleta-network/atleta/assets/8686568/13c60735-7c37-4005-a63d-7e600ea695f8)

when we deploy on atleta testnet aave it also works (deployer address is `0xCdF3ac6Be221a27e7666E57E32F84F4BB860fC0A`):

![image3](https://github.com/Atleta-network/atleta/assets/8686568/3e1bac17-6e61-4a81-9230-6735818133da)

but when we deploy on atleta, we got:

![image4](https://github.com/Atleta-network/atleta/assets/8686568/7003fd61-395d-40fa-a728-bf411a297d2f)

if we redeploy we get the same error at the same place.

after debugging we'd found that the crah happens here:

![image2](https://github.com/Atleta-network/atleta/assets/8686568/53755b7f-3c0c-4ecd-b1f7-85f28abf20b4)

if we specify the gas limit and make it a big number (but not bigger than the block size), it works:

![image6](https://github.com/Atleta-network/atleta/assets/8686568/f4064062-75a5-4a23-9b0a-a0efe0a72389)

until the next place, where gas limit is not specified (probably counted incorrectly):

![image1](https://github.com/Atleta-network/atleta/assets/8686568/0ee7a705-0def-49d0-9baa-390612647e60)

probably, atleta returns incorrect gas limit for particular transaction types. here is a link to the code of a function example:

https://github.com/aave/aave-v3-core/blob/724a9ef43adf139437ba87dcbab63462394d4601/contracts/protocol/pool/PoolConfigurator.sol#L443

**Comment by alex-draginski** [comment]
Got same error with Uniswap fork once, explicit gas limit fixed it, as mentioned above.

**Comment by ales-tsurko** [comment]
Fixed by https://github.com/Atleta-network/atleta/pull/71
