### ISSUE TITLE
Notify when we need to update chain spec

### ISSUE THREAD

**Issue by ales-tsurko** [Atleta-network/atleta#92]
As we now use chain specs exported to json, we need some mechanism to detect when we need to update the files. One possible solution is using git hook to compare `chain-spec.json` files with `chain_spec.rs` (if `chain-spec.json` is older, it's outdated), but it can have false positives and update `chain_spec.rs` not always means the chain spec have changed for one or another network configuration variant.

**Comment by hrls** [comment]
Something like this?
```shell
diff \
    <(atleta-node build-spec --chain testnet | jq --sort-keys) \
    <(cat chainspecs/_spec_file_.json | jq --sort-keys)
echo $? # 0 indicates the same files, 1 – different
```

**Comment by hrls** [comment]
Or we can pull out specs files from the repo sources and put them into GitHub artifacts.
Artifacts are available via a direct link, and we can add some script to download them.
IMO any post-build output in a repo is in some way a mess.

**Comment by ales-tsurko** [comment]
actually, we should never do this. the chainspec keeps genesis configuration and any changes to this, will lead to genesis mismatch. we should rather update the spec version and the runtime. the only changes we can do in the chainspec are things like code substitutes, bad blocks notions, forked blocks notions and some custom keys.
